### PR TITLE
Event monitoring will now work in multi-threaded unit test frameworks…

### LINKED ISSUE #320: Bug in EventRecordersMap.cs
While Unittesting with XUnit, some tests failed, because EnventRecordersMap is not thread safe.
Also this issue just apear as we run the tests within the Test Explorer of Visual Studio 2013. 
NCrunsh shows all tests as passed.

Can somebody confirm that?

Thanks and regards,
Akuzo

### PR DESCRIPTION
**Pull request by dennisdoomen**
… such as XUnit. Fixes #320.

### CODE REVIEW

File: Src/Shared/AssertionExtensions.cs [hunk 1]
```diff
@@ -617,20 +616,21 @@ public static PropertyInfoSelectorAssertions Should(this PropertyInfoSelector pr
...
+            EventRecorder[] recorders = eventSource
+                .GetType()
+                .GetEvents()
+                .Select(@event => CreateEventHandler(eventSource, @event)).ToArray();
 
             if (!recorders.Any())
             {
                 throw new InvalidOperationException(
-                    string.Format("Type {0} does not expose any events.", eventSource.GetType().Name));
+                    $"Type {eventSource.GetType().Name} does not expose any events.");
```
Comment (Meir017) [inline Src/Shared/AssertionExtensions.cs]: This is a C# 6 feature, I'm not sure you want use it since all of the project doesn't use it's features (yet)

Comment (dennisdoomen) [inline Src/Shared/AssertionExtensions.cs]: Why not? You can only build FluentAssertions with Visual Studio 2015, and it doesn't affect the target assemblies.

Comment (Meir017) [inline Src/Shared/AssertionExtensions.cs]: Just wanted to be sure it wasn't just a resharper hint you used

Comment (dennisdoomen) [inline Src/Shared/AssertionExtensions.cs]: Ah, no, but thanks for mentioning this though.

File: Tests/FluentAssertions.Shared.Specs/EventAssertionSpecs.cs [hunk 2]
```diff
@@ -311,6 +312,33 @@ public void When_the_event_parameters_do_match_it_should_not_throw()
...
+        {
+            //-----------------------------------------------------------------------------------------------------------
+            // Arrange
+            //----------------------------------------------------------------------------------------------------------
+            Action<int> action = _ =>
+            {
+                EventRaisingClass subject = new EventRaisingClass();
+                subject.MonitorEvents();
+                subject.RaiseEventWithSender();
+                subject.ShouldRaise("PropertyChanged");
```
Comment (Meir017) [inline Tests/FluentAssertions.Shared.Specs/EventAssertionSpecs.cs]: could use ````nameof(EventRaisingClass.PropertyChanged)```` instead of ````"PropertyChanged"````

Comment (dennisdoomen) [inline Tests/FluentAssertions.Shared.Specs/EventAssertionSpecs.cs]: :+1:
